datreeio/admission-webhook-datree

scripts/install.sh
success:
failure (timeout after 180 seconds):
=> fix: installation script - wait for deployment to rollout before displaying success message

deployment/admission-webhook-datree.yaml, go.mod, go.sum, kube/core-resources.yaml, main.go, pkg/clients/cliServiceClient.go, pkg/k8sMetadataUtil/k8sMetadataUtil.go, pkg/services/validationService.go
=> feat: schedule report cluster nodes

charts/datree-admission-webhook/templates/_helpers.tpl, charts/datree-admission-webhook/templates/webhook-server-clusterrole.yaml, charts/datree-admission-webhook/templates/webhook-server-clusterrolebiniding.yaml, charts/datree-admission-webhook/templates/webhook-server-deployment.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18vNJtOe0mr2s3HFKdh0IvFMGG5EmklZyM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=iQMV-Fc)
=> Webhook helm chart fixes

README.md
- added the missing helm release cleanup
- syntax highlighting for shell scripts
Signed-off-by: Dipankar Das <dipankardas0115@gmail.com>
=> docs: add uninstall for helm release

guides/developer-guide.md, pkg/controllers/validationController.go
this change is very small, just looks large
=> refactor: refactor some code in validation controller

charts/awsmp-datree-admission-webhook/templates/Chart.yaml, charts/awsmp-datree-admission-webhook/templates/templates/_helpers.tpl, charts/awsmp-datree-admission-webhook/templates/templates/clusterrole.yaml, charts/awsmp-datree-admission-webhook/templates/templates/clusterrolebinding.yaml, charts/awsmp-datree-admission-webhook/templates/templates/deployment.yaml, charts/awsmp-datree-admission-webhook/templates/templates/namespace-post-delete.yaml, charts/awsmp-datree-admission-webhook/templates/templates/namespace-post-install.yaml, charts/awsmp-datree-admission-webhook/templates/templates/role.yaml, charts/awsmp-datree-admission-webhook/templates/templates/rolebinding.yaml, charts/awsmp-datree-admission-webhook/templates/templates/service.yaml, charts/awsmp-datree-admission-webhook/templates/templates/serviceaccount.yaml, charts/awsmp-datree-admission-webhook/templates/templates/wait-server-ready-post-install.yaml, charts/awsmp-datree-admission-webhook/templates/templates/webhook-with-cert-secrets.yaml, charts/awsmp-datree-admission-webhook/templates/values.schema.json, charts/awsmp-datree-admission-webhook/templates/values.yaml, charts/awsmp-datree-free-admission-webhook/templates/Chart.yaml, charts/awsmp-datree-free-admission-webhook/templates/templates/_helpers.tpl, charts/awsmp-datree-free-admission-webhook/templates/templates/clusterrole.yaml, charts/awsmp-datree-free-admission-webhook/templates/templates/clusterrolebinding.yaml, charts/awsmp-datree-free-admission-webhook/templates/templates/deployment.yaml, charts/awsmp-datree-free-admission-webhook/templates/templates/namespace-post-delete.yaml, charts/awsmp-datree-free-admission-webhook/templates/templates/namespace-post-install.yaml, charts/awsmp-datree-free-admission-webhook/templates/templates/role.yaml, charts/awsmp-datree-free-admission-webhook/templates/templates/rolebinding.yaml, charts/awsmp-datree-free-admission-webhook/templates/templates/service.yaml, charts/awsmp-datree-free-admission-webhook/templates/templates/serviceaccount.yaml, charts/awsmp-datree-free-admission-webhook/templates/templates/wait-server-ready-post-install.yaml, charts/awsmp-datree-free-admission-webhook/templates/templates/webhook-with-cert-secrets.yaml, charts/awsmp-datree-free-admission-webhook/templates/values.schema.json, charts/awsmp-datree-free-admission-webhook/templates/values.yaml
depends on #DAT-feat-datree-lib-chart
=> feat: awsmp datree use datree lib

charts/datree-admission-webhook/Chart.yaml
=> Update Chart.yaml version

.github/workflows/release_to_prod.yaml, .github/workflows/release_to_staging.yaml, .github/workflows/unit-tests.yaml, test.yaml
- ci: update gh actions pakcages
- fix: run unit test ans build on each pr
=> ci: github actions update packages

charts/datree-admission-webhook/templates/deployment.yaml
setting boolean values in values.yaml was broken, this fixes the bug
=> fix: wrap deployment env variables in double quotes

Makefile, charts/datree-admission-webhook/templates/cluster-scan-job.yaml, charts/datree-admission-webhook/values.yaml
- helm: use values for scan job image and make staging install
- helm: use values for scan job image and make staging install
=> make helm install staging

Makefile, charts/datree-admission-webhook-awsmp/templates/NOTES.txt, charts/datree-admission-webhook-awsmp/templates/deployment.yaml, charts/datree-admission-webhook-awsmp/values.yaml, pkg/services/validationService.go, scripts/uninstall.sh
1. return a success message when webhook installed with a token
2. return a warning message when webhook is installed without a token
3. early return and display a warning when applying a resource while the webhook does not have a token
=> feat: make token optional in AWS marketplace, returning a warning instead of validating

charts/datree-admission-webhook/templates/deployment.yaml, pkg/clients/cliServiceClient.go, pkg/enums/enums.go, pkg/services/validationService.go
This reverts commit 91fab3904deb09f9163769ee3acd969e487dcdce.
=> Revert "feat: send cluster name in policy check results (#240)"

.github/workflows/release_to_staging.yaml
- fix: add cache to docker build
- fix: remove cache
=> DAT 4673 docker build cache gha

pkg/services/validationService.go
=> fix: skip resource validation on getting prerun data failure

charts/datree-admission-webhook/templates/deployment.yaml, go.sum, main.go, pkg/clients/cliServiceClient.go, pkg/controllers/validationController.go, pkg/controllers/validationController_test.go, pkg/enums/enums.go, pkg/errorReporter/errorReporter.go, pkg/k8sMetadataUtil/k8sMetadataUtil.go, pkg/serviceState/serviceState.go, pkg/services/validationService.go
- feat: add state class
- fix: add state intialization
- feat: add cluster name to webhook
- feat: use custom cli client
- fix: test use custom cli client
- feat: go mod tidy
- feat: add state as a dependency injection
- feat: remove unnecessary panic
- feat: reuse state variables
- test: fix test dependencies
- fix: wrong client issue
- feat: remove duplicated cli-service-client
- feat: remove duplicated import
- feat: make validation service dependency public
- feat: remove duplicated cliClient
- feat: remove unnecessary dependency
- feat: delete unnecessary new function
=> feat: enrich webhook scanner panic unexpected errors

charts/datree-admission-webhook/templates/cluster-scan-cronjob.yaml, charts/datree-admission-webhook/values.yaml
Hey ho, 
in order to fix this problem https://github.com/argoproj/argo-cd/issues/8586 
scanJob.annotations should be added :)
This fixes the problem for me at least 
Greets,
Benjamin
=> feat: add annotations to one-time scanJob

pkg/services/resourcesFilterService.go
* This is , supposedly,  one of the OKD managers. Currently this one will cause less noise.
=> fix: allow OKD resources with manager openshift-controller-manager

pkg/services/validationService.go
=> feat: add passing webhook evaluations message to warnings

index.yaml
This reverts commit 392a78496d1dfaadf63da205198e24a3003f097f.
=> Revert "Update index.yaml" (deletes release 0.3.49)

index.yaml
=> revert helm chart latest 2905

charts/datree-admission-webhook/templates/validations/validations.yaml
=> fix: don't allow the same policy to be used more than once in multiplePolicies

scripts/troubleshoot.sh
=> fix: add data of scanner and webhook to troubleshoot script

pkg/logger/logger.go
ignore zap.Sync - https://github.com/uber-go/zap/issues/328
fixed logs:
=> fix: ignore zap.sync error and support time and json encoder

pkg/controllers/validationController.go
=> feat: add admission review request to outgoing log

README.md, Tiltfile, charts/datree-admission-webhook/README.md, charts/datree-admission-webhook/templates/namespace-post-delete.yaml, charts/datree-admission-webhook/values.yaml
fix: remove unnecessary debugging ports
feat: devMode
=> feat: devMode

charts/datree-admission-webhook/templates/validations/validations.yaml
* add error message when someone is trying to install on old cluster (v1.18.x)
=> feat: add validation error message

pkg/services/validationService.go
=> fix: warn about skipped resources that skipped by skip list

README.md, charts/datree-admission-webhook/README.md, charts/datree-admission-webhook/templates/deployment.yaml, charts/datree-admission-webhook/values.schema.json, charts/datree-admission-webhook/values.yaml, internal/fixtures/values.dev.yaml, pkg/controllers/validationController_test.go, pkg/enums/enums.go, pkg/serviceState/serviceState.go, pkg/services/validationService.go
- feat: add the ability to choose which warning to present
- fix: test
- feat: add json schema validation
=> DAT 5324 introduce warnings flag
